web:
  build: .
  ports:
    - "8080:80"
  volumes:
    - .:/var/www/html
    - ./dockerconfig/virtualhosts.conf:/etc/apache2/sites-enabled/virtualhosts.conf
    - ./dockerconfig/php.ini:/usr/local/etc/php/php.ini
    - ./dockerconfig/composer.phar:/var/www/html/composer.phar
    - ./dockerconfig/start.sh:/var/www/html/start.sh
  links:
    - mysql

mysql:
  image: mysql:5.7
  ports:
    - "3307:3306"
  environment:
    MYSQL_ROOT_PASSWORD: 123456
    MYSQL_USER: dev
    MYSQL_PASSWORD: 123456
    MYSQL_DATABASE: mydb
